### ISSUE TITLE
[typo] README

### ISSUE THREAD

**Issue by eveningkid** [Themimitoof/themimitoof#1]
Salut Mika,

> For my love of infrastructures **and for my and for my** infinite curiosity, I also wear the hat of a system and network administrator.

J'ai direct pensé à "formi, formi, formidable" !

Je doute que ce n'était pas volontaire :)

**Comment by Themimitoof** [comment]
Salut Arnaud :wave: 

Merci pour avoir spotté la typo ! Corrigé avec : https://github.com/Themimitoof/themimitoof/commit/f45fdb3ede25eba04f487f8e68c5bddd35ab4757 ;)
